######################################################################
# Automatically generated by qmake (2.01a) Sun 21. Nov 12:25:09 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += inspirebrowser
SUBDIRS += inspireremote
