######################################################################
# Automatically generated by qmake (2.01a) Sun 21. Nov 12:25:09 2010
######################################################################

TEMPLATE = subdirs
CONFIG += ordered

# Directories
SUBDIRS += inspirelib
SUBDIRS += browser
SUBDIRS += remote
SUBDIRS += plugin_browserjs
SUBDIRS += plugin_systemjs
SUBDIRS += plugin_videojs_vlc
SUBDIRS += plugin_commandserver
